 version: 2 
 jobs:
   one:
     docker:
       - image: circleci/php:7.4.6
     steps:
       - checkout
       - run: echo "A first hello"
   two:
     docker:
       - image: circleci/php:7.4.6
     steps:
       - checkout
       - run: echo "A more familiar hi"
 workflows:
   version: 2
   one_and_two:
     jobs:
       - one
       - two
