 version: 2 
 jobs:
   build:
     docker:
       - image: circleci/php:7.4.6
     steps:
       - checkout
       - run: echo "A first hello"
   deploy:
     machine:
       - image: circleci/classic:edge
     steps:
       - checkout
       - add_ssh_keys:
       - run: ssh ${USER_NAME}@${HOST_NAME} 'cd ~/suzuki/ && git pull'
 workflows:
   version: 2
   build_and_deploy:
     jobs:
       - build
       - deploy:
           requires:
             - build
           filters:
             branches:
               only:
                 - master
