 version: 2 
 jobs:
   one:
     docker:
       - image: circleci/php:7.4.6
     steps:
       - checkout
       - run: echo "A first hello"
   two:
     machine:
       - image: circleci/classic:edge
     steps:
       - checkout
       - add_ssh_keys:
       - run: ssh ${USER_NAME}@${HOST_NAME} 'cd ~/suzuki/ && git pull'
 workflows:
   version: 2
   one_and_two:
     jobs:
       - one
       - two:
           requires:
             - one
           filters:
             branches:
               only:
                 - master
